name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Models
        run: |
          mkdir -p model
          unzip -o model1.zip -d model/ || true
          unzip -o model2.zip -d model/ || true

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libsqlite3-dev libbz2-dev python3-dev python3-setuptools build-essential
          pip3 install --user --upgrade buildozer cython==0.29.33 virtualenv
          
      - name: Setup Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          yes | buildozer init
          
          # Force Stable Python and p4a settings to avoid Python 3.14 errors
          echo "android.python_recipe = python3" >> buildozer.spec
          echo "p4a.branch = master" >> buildozer.spec
          
          # Add extra file extensions
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,mp4,ttf,db/g' buildozer.spec
          
          # Requirements (Clean & Compatible)
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd,sqlite3,edge-tts,SpeechRecognition,gtts,pydantic==1.10.13,groq,httpx,plyer/g' buildozer.spec
          
          # Add Android Permissions
          sed -i 's/# android.permissions = INTERNET/android.permissions = INTERNET, RECORD_AUDIO/g' buildozer.spec
          
          # Auto-Accept Android SDK Licenses
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          export PIP_DISABLE_PIP_VERSION_CHECK=1
          yes | buildozer -v android debug

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: AiTeacherApp-APK
          path: bin/*.apk
