- name: Setup Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          yes | buildozer init
          
          # Force Python version to 3.11 (Stable for Android)
          echo "android.python_recipe = python3" >> buildozer.spec
          echo "p4a.branch = master" >> buildozer.spec
          
          # Add extra file extensions
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,mp4,ttf,db/g' buildozer.spec
          
          # Requirements
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd,sqlite3,edge-tts,SpeechRecognition,gtts,pydantic==1.10.13,groq,httpx,plyer/g' buildozer.spec
          
          # Add Android Permissions
          sed -i 's/# android.permissions = INTERNET/android.permissions = INTERNET, RECORD_AUDIO/g' buildozer.spec
          
          # Auto-Accept Android SDK Licenses
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
